spring.application.name=urlshortener
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=sayone

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.redis.host=localhost
spring.redis.port=6379

# Custom Application Properties
app.base-url=http://localhost:8000
app.default-ttl-days=30
